### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kyumho** [5LionShoppingMall/ShoppingMall_BE#2]
- [x] **초기 ERD에 따라서 엔티티 간의 연관관계 구현**
- [x] **Next.js 와 Spring Framework 연동 (cors 문제)** 
- [x] **커뮤니티 게시판 CRUD / ERD 및 Entity 생성**
- [x] **메인 페이지 생성** 
- [x] **역할 분담**

**Comment by Son-Gyeongi** [comment]
'커뮤니티 게시판 CRUD / ERD 및 Entity 생성' 이 부분도 추가하면 좋을 거 같습니다!

**Comment by kyumho** [comment]
> '커뮤니티 게시판 CRUD / ERD 및 Entity 생성' 이 부분도 추가하면 좋을 거 같습니다!

추가했습니다!! ㅎㅎ
